export const cartActionTypes = {
	TOGGLE_CART_DROPDOWN: 'TOGGLE_CART_DROPDOWN',
	// CLOSE_CART_DROPDOWN: 'CLOSE_CART_DROPDOWN', 
	ADD_ITEM_TO_CART: 'ADD_ITEM_TO_CART',
	REMOVE_ITEM_FROM_CART: 'REMOVE_ITEM_FROM_CART',
	REMOVE_PRODUCT: 'REMOVE_PRODUCT',
	GET_TOTAL_BALANCE_CART: 'GET_TOTAL_BALANCE_CART'
}